version: '3'

services:
  todo_web:
    image: nginx:latest
    container_name: todo-web
    ports:
      - "80:80"
    volumes:
      - dist:/var/www
      - ./docker/nginx/todo-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_network
  web:
    image: nginx:latest
    container_name: server-web
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo_network
  
  todo_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: todo_server
    volumes:
      - .:/var/www
    networks:
      - todo_network
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1

networks:
  todo_network:
    driver: bridge
