version: '3'

services:
  todo_web:
    image: nginx:latest
    container_name: todo-web
    ports:
      - "80:80"
    volumes:
      - ./dist:/var/www
      - ./docker/nginx/todo-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
  web:
    image: nginx:latest
    container_name: server-web
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
  
  todo_server:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: todo_server
    volumes:
      - .:/var/www
    networks:
      - docker-network

networks:
  docker-network:
    external: true
